### ISSUE TITLE
Dropcaps

### ISSUE THREAD

**Issue by hadley** [hadley/mastering-shiny#288]
```css
p.dropcap:first-letter {
  color: #333;
  float: left;
  font-size: 6rem;
  line-height: 1;
  padding-right: 8px;
  margin-left: 0;
  display: inline-block;
  margin-top: -10px;
}
```
